PlanetExpress/config/routes.rb
PlanetExpress::Engine.routes.draw do
  resources :zoidbergs
  root 'zoidbergs#index'
end

PlanetExpress/app/models/planet_express/zoidberg.rb
module PlanetExpress
  class Zoidberg
    include ::Mongoid::Document
    include ::Mongoid::Timestamps
    field :name, type: String
  end
end

PlanetExpress/app/controllers/planet_express/application_controller.rb
module PlanetExpress
  class ApplicationController < ActionController::Base
  end
end

PlanetExpress/app/controllers/planet_express/zoidbergs_controller.rb
require_dependency "planet_express/application_controller"

module PlanetExpress
  class ZoidbergsController < ApplicationController
    before_action :set_zoidberg, only: [:show, :edit, :update, :destroy]

    # GET /zoidbergs
    def index
      @zoidbergs = Zoidberg.all
    end

    # GET /zoidbergs/1
    def show
    end

    # GET /zoidbergs/new
    def new
      @zoidberg = Zoidberg.new
    end

    # GET /zoidbergs/1/edit
    def edit
    end

    # POST /zoidbergs
    def create
      @zoidberg = Zoidberg.new(zoidberg_params)

      if @zoidberg.save
        redirect_to @zoidberg, notice: 'Zoidberg was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /zoidbergs/1
    def update
      if @zoidberg.update(zoidberg_params)
        redirect_to @zoidberg, notice: 'Zoidberg was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /zoidbergs/1
    def destroy
      @zoidberg.destroy
      redirect_to zoidbergs_url, notice: 'Zoidberg was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_zoidberg
        @zoidberg = Zoidberg.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def zoidberg_params
        params.require(:zoidberg).permit(:name)
      end
  end
end

PlanetExpress/app/helpers/planet_express/application_helper.rb
module PlanetExpress
  module ApplicationHelper
  end
end

PlanetExpress/app/helpers/planet_express/zoidbergs_helper.rb
module PlanetExpress
  module ZoidbergsHelper
  end
end

PlanetExpress/app/views/layouts/planet_express/_notifications.html.haml
- if (warning=flash[:warning]).present? || notice.present?
  .notifications_container
    - if warning.present?
      .alert.alert-danger
        .close{data: {dismiss: 'alert'}} &times;
        = warning
    - if notice.present?
      .alert.alert-success
        .close{data: {dismiss: 'alert'}} &times;
        = notice

PlanetExpress/app/views/layouts/planet_express/application.html.haml
!!!
%html
  %head
    %title Planet Express Engine

PlanetExpress/app/views/planet_express/zoidbergs/_form.html.haml
= form_for @zoidberg do |f|
  - if @zoidberg.errors.any?
    #error_explanation
      %h2= "#{pluralize(@zoidberg.errors.count, "error")} prohibited this zoidberg from being saved:"
      %ul
        - @zoidberg.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

PlanetExpress/app/views/planet_express/zoidbergs/edit.html.haml
%h1 Editing zoidberg

= render 'form'

= link_to 'Show', @zoidberg
\|
= link_to 'Back', zoidbergs_path

PlanetExpress/app/views/planet_express/zoidbergs/index.html.haml
%h1 Listing zoidbergs

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @zoidbergs.each do |zoidberg|
    %tr
      %td= zoidberg.name
      %td= link_to 'Show', zoidberg
      %td= link_to 'Edit', edit_zoidberg_path(zoidberg)
      %td= link_to 'Destroy', zoidberg, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Zoidberg', new_zoidberg_path

PlanetExpress/app/views/planet_express/zoidbergs/new.html.haml
%h1 New zoidberg

= render 'form'

= link_to 'Back', zoidbergs_path

PlanetExpress/app/views/planet_express/zoidbergs/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @zoidberg.name

= link_to 'Edit', edit_zoidberg_path(@zoidberg)
\|
= link_to 'Back', zoidbergs_path